export const loadsConfig =  [{
  pickupDate: "",
  truckId: "",
  driverName: "",
  driverId: 0,
  loadNumber: "",
  brokerName: "",
  brokerId: 0,
  shipper:"",
  consignee:"",
  pickUpCityState: "",
  dropOffCityState: "",
  pickUpAddress: "",
  dropOffAddress: "",
  payment: 0,
  loadedMiles: 0,
  emptyMiles: 0,
  mileage: 0,
  dollarPerMile: 0,
  fuelCost: 0,
  driverPay: 0,
  dispatchFee: 0,
  lumper: 0,
  detention: 0,
  detentionDriverPay: 0,
  secondStopDriverPay: 0,
  lateFee: 0,
  toll: 0,
  roadMaintenance: 0,
  otherExpenses: 0,
  totalExpenses: 0,
  profit: 0,
  commodity: "",
  weight: 0,
  trailer: "",
  confirmFilePath: ""
}]
